### ISSUE TITLE
I cannot install to yii 2.0.5

### ISSUE THREAD

**Issue by nonnyohiyo** [yiisoft/yii2-jui#25]
I cannot install to yii 2.0.5

**Comment by cebe** [comment]
please elaborate.

**Comment by akhildar** [comment]
Not able to download and getting below error:


Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: failed t
o open stream: A connection attempt failed because the connected party did not p
roperly respond after a period of time, or established connection failed because
 connected host has failed to respond.

https://packagist.org could not be fully loaded, package information was loaded
from the local cache and may be out of date
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no
matching package found.
    - Removal request for yiisoft/yii2-jui == 2.0.0.0-beta
    - Installation request for yiisoft/yii2-jui ~2.0.0 -> satisfiable by yiisoft
/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.0-beta].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

**Comment by cebe** [comment]
> A connection attempt failed because the connected party did not p
> roperly respond after a period of time, or established connection failed because
> connected host has failed to respond.

sounds like an internet connection problem.
