### ISSUE TITLE
 $.fn.button.noConflict is not a function

### ISSUE THREAD

**Issue by ijackwu** [yiisoft/yii2-jui#62]
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11.2.
| PHP version      | 5.5.9-1ubuntu4.21
| Operating system | ubuntu4.21

![image](https://cloud.githubusercontent.com/assets/12708015/25812201/1fe594ec-3448-11e7-91f1-cb4342768de0.png)

**Comment by andrtechno** [comment]
```
Dialog::begin([
    'clientOptions' => [
        'modal' => true,
    ],
]);
echo 'Dialog contents here...';
Dialog::end();
```

> TypeError: $.fn.button.noConflict is not a function

**Comment by fmartiner** [comment]
Same problem with Yii2 version 2.0.14.
With Bootstrap and Dialog of JUI.

Solution is add .noConflict in \vendor\yiisoft\yii2-jui\src\Dialog.php at line 45 

if ($.fn.button.noConflict) {
       var bootstrapButton = $.fn.button.noConflict(); 
       $.fn.bootstrapBtn = bootstrapButton;
}",

**Comment by lubosdz** [comment]
After upgrade to newest jQuery, UI, bootstrap I am receiving error with modal Dialog grid page:

`TypeError: $.fn.button.noConflict is not a function`

changing [the line](https://github.com/yiisoft/yii2-jui/blob/master/src/Dialog.php#L45) to:

```
if ($.fn.button && $.fn.button.noConflict !== undefined) {
   ...
}
```

does not break JS code even if method `noConflict()` would be removed from the `button` object.
Though I am not sure whether this would be perfect solution ..

**Comment by hipogea** [comment]
After change these line, it works...!
Thanks a lot

**Comment by haohetao** [comment]
我也是这个问题，为什么这个bug还没修复

**Comment by machour** [comment]
@haohetao because you didn't provide a PR yet :)

**Comment by lazarevicivica** [comment]
I had the same issue and solved it with MuvShots repository. I think yii/jui should be fixed too.

**Comment by perochak** [comment]
Issue still there. Main repo should be updated

**Comment by lubosdz** [comment]
I guess whole CI build needs to be reviewed, coz all builds fail for long ago fixed issues e.g.

* [7.4](https://travis-ci.com/github/yiisoft/yii2-jui/jobs/396710285#L529) - Cannot use 'Object' as class name as it is reserved in /home/travis/build/yiisoft/yii2-jui/vendor/yiisoft/yii2/base/Object.php on line 77
* [7.1](https://travis-ci.com/github/yiisoft/yii2-jui/jobs/396710278#L533) - There should be the jQuery UI Selectable plugin initialization for myselectableitems

The fix itself should not cause any failures. Since I am not familiar with these builds I am not sure how to fix it.

**Comment by samdark** [comment]
Yes, we should switch to GitHub actions.
